apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-d-2329146
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-d-2329146
  template:
    metadata:
      labels:
        app: devops-d-2329146
    spec:
      containers:
        - name: devops-d-2329146
          image: devops-d-2329146:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80